# Feel free to BuyMeACoffee - The infrastructure that the site runs on is provided to users free of charge, but costs me, so if you can help out, that'd be fab!

custom: ['https://www.buymeacoffee.com/ibhgnEQXu']
