<?php
	try {
		require(__DIR__ . "/config/config.php");
		require(__DIR__ . "/classes/class.DBConnection.php");
		require(__DIR__ . "/classes/class.ESECEngine.php");

		//header("Content-Type: application/json");
		header("Content-Type: text/calendar");

		$ESECEngine			=	new ESECEngine();
		$datetime			=	new DateTime();

		$datetime_start		=	new DateTime("2022-10-17");
		$datetime_end		=	new DateTime("2023-04-24");

		$interval = DateInterval::createFromDateString('1 day');
		$period = new DatePeriod($datetime_start, $interval, $datetime_end);

		$disconnectionRota	=	$ESECEngine->fetchDisconnectionRota($_GET['load_block']);

		$ESECEngine->handleLevel0();

		echo "BEGIN:VCALENDAR" . PHP_EOL;
		echo "VERSION:2.0" . PHP_EOL;
		echo "PRODID:icalendar-ruby" . PHP_EOL;
		echo "CALSCALE:GREGORIAN" . PHP_EOL;
		echo "X-WR-CALNAME:UK Scheduled Power Disconnections" . PHP_EOL;
		echo "X-APPLE-LANGUAGE:en" . PHP_EOL;
		echo "X-APPLE-REGION:GB" . PHP_EOL;

		foreach ($period as $dt) {
			foreach ($disconnectionRota as $dr) {
				if ($dt->format("N") == $dr->dow) {
					$eventIdentifier	=	$dr->dow . "/" . $dr->pid . "/" . $dr->lb . "/" . $dr->lod;

					echo "BEGIN:VEVENT" . PHP_EOL;
					echo "DTSTAMP:" . $dt->format("Ymd\T") . str_replace(':', '', $dr->st) . "Z" . PHP_EOL;
					//UID:c6a54f5e-bd22-3c9c-b4e3-2b36dc5c3d20
					echo "DTSTART:" . $dt->format("Ymd\T") . str_replace(':', '', $dr->st) . "Z" . PHP_EOL;
					echo "DTEND:" . $dt->format("Ymd\T") . str_replace(':', '', $dr->et) . "Z" . PHP_EOL;
					echo "CLASS:PUBLIC" . PHP_EOL;
					echo "DESCRIPTION:Event Identifier: {$eventIdentifier}\\n" . PHP_EOL;
					echo " ==========\\n" . PHP_EOL;
					echo " This calendar will automatically update based on the current National\\n" . PHP_EOL;
					echo " Level of Disconnection\\n" . PHP_EOL;
					echo " ==========\\n" . PHP_EOL;
					echo " Generated by ukesec.info\\n" . PHP_EOL;
					echo " Free, open-source UK ESEC Tool\\n" . PHP_EOL;
					echo " ==========\\n" . PHP_EOL;
					echo " CURRENTLY IN DEVELOPMENT\\n" . PHP_EOL;
					echo " NOT TO BE USED AS LIVE DATA\\n" . PHP_EOL;
					echo "SUMMARY;LANGUAGE=en:Disconnection Event - {$eventIdentifier}" . PHP_EOL;
					echo "TRANSP:TRANSPARENT" . PHP_EOL;
					echo "END:VEVENT" . PHP_EOL;
					//echo $dt->format("jS F Y ") . $dr->st . " - " . $dt->format("jS F Y ") . $dr->et . PHP_EOL;
				}
			}
		}

		echo "END:VCALENDAR" . PHP_EOL;

	} catch (Exception $e) {
		echo $e;
	}